Create diary
MasahiroOhsaki/workdiary pull request #15
Opened 2019-09-12 12:59 UTC by MasahiroOhsaki

・Diaryモデル作成
・Diariesコントローラー作成
・application.html.erbのビュー作成

2019-09-12 13:44 UTC, toyokappa requested changes
以前の指摘をうまく踏襲できていていいと思いました。少し修正点が合ったのでご確認お願いします。

2019-09-12 13:44 UTC, toyokappa commented on app/assets/stylesheets/diaries.scss
> +// Place all the styles related to the Diaries controller here.
こちらのファイルは不要なので削除しましょう。

2019-09-12 13:44 UTC, toyokappa commented on app/controllers/diaries_controller.rb
> +    @diaries = Diary.all.order(date: "DESC")
細かいですが、`order(date: :desc)`という感じでも書けるので参考までに！

2019-09-12 13:44 UTC, toyokappa commented on app/views/diaries/_errormessage.html.erb
> +<% if diary.errors.any? %>
flashメッセージ用のパーシャルは今後も他の入力系で使い回すことになりそうなので、ここの階層に作成しないほうが良いかなぁと思います。また、少し細かいですが、単語的には`error message`だと思うので、ファイル名も`_error_message`の方が見やすいかなぁと思います（errormessageだとこれで一単語っぽくかつ見慣れないので違和感があるなぁと感じました）

2019-09-12 13:44 UTC, toyokappa commented on app/views/diaries/new.html.erb
> +<%= render 'errormessage', diary: @diary %>
上記の通り外でも使い回す可能性が高いので、レイアウト側に組み込めるとベストです。

2019-09-12 15:30 UTC, massa-potato commented on app/views/diaries/new.html.erb
> +<%= render 'errormessage', diary: @diary %>
layout/application.html.erbのほうにrenderを記述したらよい、ということですかね。
変数の扱いが戸惑ったのですが調べてやってみました。

2019-09-13 00:14 UTC, toyokappa commented on app/views/diaries/new.html.erb
> +<%= render 'errormessage', diary: @diary %>
あーすいません、flashメッセージのパーシャルと勘違いをしていました。そうなるとlayoutsに置くのは難しいので、修正いただいた中で申し訳ないですがパーシャルは別に分ける対応はOKで、ここに戻してもら得たらと思います:bow:

なお、ゆくゆくはフォームのフィールドの下に個別のエラーメッセージが表示できるのが良いと思いますので、今ではなくても良いですがどこかのタイミングでリファクタできると良いかと思います！

2019-09-14 02:02 UTC, toyokappa approved these changes
LGTM！次に進みましょう！

2019-09-18 13:29 UTC, merged