Create work
MasahiroOhsaki/workdiary pull request #16
Opened 2019-09-18 13:12 UTC by MasahiroOhsaki

・Workモデル作成
・Worksコントローラー作成
・new, create, index, show, edit, update, destroyアクション作成

2019-09-18 14:06 UTC, toyokappa requested changes
確認しました。修正お願いします。

2019-09-18 14:06 UTC, toyokappa commented on app/assets/stylesheets/works.scss
> +// Place all the styles related to the works controller here.
こちらのファイルは不要なので削除お願いします。generatorの設定でcss作成されないようにしちゃったほうが良いかもですね。

2019-09-18 14:06 UTC, toyokappa commented on db/migrate/20190916114303_change_data_date_to_work.rb
> +    change_column :works, :date, :date
開発初期段階なので、CreateWorks側のmigrationファイルの方を書き換えてしまって`bin/rails db:migrate:reset` を実行したほうが不要なmigrationファイルが増えずに良いかなぁと思いました。

2019-09-18 14:06 UTC, toyokappa commented on db/migrate/20190916034815_create_works.rb
> +      t.datetime :date
仕様を把握しきれていなかったのですが、Workにもdateを入力する必要はあるのでしょうか？DiaryにWorkが紐づくイメージだったので、Diaryで登録した日付の作業（Work）を追加するイメージでいました。

2019-09-18 14:06 UTC, toyokappa commented on app/models/diary.rb
> +  has_many :works
この設定のみだと仮にDiraryを削除したときに、紐づくWorkは残りますがそれは意図した挙動ということで良いでしょうか？

2019-09-18 14:06 UTC, toyokappa commented on app/models/work.rb
> +  with_options presence: true do
下記のような書き方が一般的かなぁと思うのですが、あえて`with_option`で囲った理由はありますか？（珍しい書き方なので純粋に気になりました）
```ruby
validates :category, presence: true
validates :title, presence: true
```

2019-09-18 14:06 UTC, toyokappa commented on app/controllers/works_controller.rb
> +    @work = Work.new
これでも動きますが、関連を持ってますよ、というのを明示するために`@work = @diary.works.build`の方が良いかなぁと思いました。

2019-09-18 14:06 UTC, toyokappa commented on app/controllers/works_controller.rb
> +    @work = @diary.works.create(work_params)
`create`ではなく`build`の方がいいですね。

2019-09-18 14:06 UTC, toyokappa commented on config/routes.rb
> +    resources :works
`index`や`show`のルーティングは不要なので、生成しないように設定しましょう。

2019-09-18 14:06 UTC, toyokappa commented on app/views/diaries/index.html.erb
> +        <td><%= link_to "ワークを追加", new_diary_work_path(diary.id) %></td>
細かいですが`new_dirary_work_path(diary)`でもいいかなぁと思いました。

2019-09-18 14:06 UTC, toyokappa commented on app/views/diaries/index.html.erb
> +          <td><%= link_to "edit", [:edit, work.diary, work] %></td>
`edit_diary_work_path(diary, work)`の方が良いと思います。この配列の表記だけだとパット見どこへのなのかが読み取りづらいです。

2019-09-18 14:06 UTC, toyokappa commented on app/views/diaries/index.html.erb
> +          <td><%= link_to "delete", [work.diary, work], method: :delete, data: {confirm: "このワークを消して大丈夫？"} %></td>
こちらも配列ではなくpathで書きましょう。

2019-09-18 14:06 UTC, toyokappa commented on app/views/diaries/show.html.erb
> +      <td><%= link_to "edit", [:edit, work.diary, work] %></td>
こちらもですね。

2019-09-18 14:06 UTC, toyokappa commented on app/views/diaries/show.html.erb
> +      <td><%= link_to "delete", [work.diary, work], method: :delete, data: {confirm: "このワークを消して大丈夫？"} %></td>
こちらも。

2019-09-18 14:06 UTC, toyokappa commented on app/views/diaries/index.html.erb
> +      <% diary.works.each do |work| %>
N+1問題をはらんでいるので修正しましょう。

2019-09-18 14:06 UTC, toyokappa commented on app/views/works/_form.html.erb
> +<%= form_with(model: [@diary, @work], local: true) do |form| %>
パーシャル上で直接インスタンス変数を呼ぶのはあまり好ましくないです。

2019-09-19 03:03 UTC, MasahiroOhsaki commented on db/migrate/20190916114303_change_data_date_to_work.rb
> +    change_column :works, :date, :date
なるほどです。下のと合わせて修正してみます。

自分用メモ
https://ja.stackoverflow.com/questions/39554/migration%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A7%E3%82%AB%E3%83%A9%E3%83%A0%E3%82%92%E8%BF%BD%E5%8A%A0-%E5%89%8A%E9%99%A4%E3%81%97%E3%81%A6%E3%82%82schema-rb%E3%81%AB%E5%8F%8D%E6%98%A0%E3%81%97%E3%81%AA%E3%81%84%E3%81%AE%E3%81%AF%E3%81%AA%E3%81%9C%E3%81%8B

2019-09-19 03:05 UTC, MasahiroOhsaki commented on db/migrate/20190916034815_create_works.rb
> +      t.datetime :date
Workで日付を入力できるようにと最初想定していたのですが、指摘の通り必要はなさそうですね。Viewに日付を表示するだけでフォームは削除します。
併せてカラムにdateを作らないようにすればよさそうですね。

2019-09-19 03:14 UTC, MasahiroOhsaki commented on app/models/diary.rb
> +  has_many :works
設定忘れでした！修正します。

2019-09-19 03:19 UTC, MasahiroOhsaki commented on app/models/work.rb
> +  with_options presence: true do
こちらの方が自然なのですね。調べたらまとめて書く書き方がでてきたので使ってみただけなのであまり深い意味はなく。直してみます。
https://qiita.com/erb_owl/items/145958e57224be5343c9

2019-09-19 03:24 UTC, MasahiroOhsaki commented on app/views/works/_form.html.erb
> +<%= form_with(model: [@diary, @work], local: true) do |form| %>
前回指摘いただいて気を付けていたのですが、エラーに対応している間に色々書き替えて試していた際にインスタンス変数にしてしまっていたようです。修正します。

2019-09-19 14:44 UTC, MasahiroOhsaki commented on app/controllers/works_controller.rb
> +    @work = @diary.works.create(work_params)
調べたら関連付けされたモデルのオブジェクト生成の時はbuildがいいのですね。
new, create, buildの違いがあいまいなので一度整理してみます。

2019-09-20 13:13 UTC, MasahiroOhsaki commented on app/views/diaries/index.html.erb
> +      <% diary.works.each do |work| %>
こんなのあるんですね。ちょっと完全に理解できてるかまだ怪しいですが一応直して
    <% diary.works.includes(:diary).each do |work| %>
としました。

自分用メモ
https://qiita.com/hirotakasasaki/items/e0be0b3fd7b0eb350327

2019-09-21 01:43 UTC, toyokappa commented on app/views/diaries/index.html.erb
> +      <% diary.works.each do |work| %>
参考にしたページは良いのですが、対応方法が間違っています。これだと意味がないです。Controller側で下記の通り設定してください。

```ruby
@diaries = Diary.all.includes(:works)
```

用法の理解がたりなさそうなのでもう一度参考記事もしくは`includes`が何をしているのかを見てみるとよいかと思います。

2019-09-21 01:54 UTC, toyokappa requested changes
２件修正をお願いします！

2019-09-21 01:54 UTC, toyokappa commented on config/routes.rb
> +    resources :works, except: [:index, :show]
`except`で使わないものを弾く（ブラックリスト）形式で設定を行うのではなく、`only`で使うものを設定する（ホワイトリスト）方式のほうが良いかと思います。routingをパット見たときにどのアクションが定義されているのかがわかりやすい（exceptだと引き算して考えないといけない）ので。

2019-09-22 12:19 UTC, toyokappa requested changes
LGTMです。次に進みましょう。

2019-09-22 13:14 UTC, toyokappa approved these changes
すいません、間違ってChange Requestでコメント書いちゃいました:bow:

2019-09-23 15:09 UTC, merged