Create template【WIP】
MasahiroOhsaki/workdiary pull request #17
Opened 2019-10-04 05:01 UTC by MasahiroOhsaki

①プルダウンリストからテンプレート名を選択して
②「テンプレート挿入」をクリックしたら
③そのテンプレートのbodyをとってきて
④workの詳細フォームにテンプレートのbodyが反映される
（この部分にAjax使用想定）

という機能を作ろうと思っているのですが、③の部分でうまくidを取得できないでいるのですが、どう考えたらいいでしょう？
（ビューズwork/newからパーシャル化したwork/_formの16行目でActionController::UrlGenerationErrorが発生して、エラー文ではテンプレートidが取得されていない様子）

2019-10-06 12:58 UTC, happa commented
@MasahiroOhsaki 
流れは良いかと思いました。あと途中まで実装しているコードもおしい感じでしょうか。私が書いてみたものを別のPull requestにしてあります。

2019-10-16 06:53 UTC, toyokappa requested changes
コメントしました。確認お願いします。

2019-10-16 06:53 UTC, toyokappa commented on app/controllers/templates_controller.rb
> +    session[:diary_id] = params[:format]
明示的に`params[:diary_id]`から取ってこれるようにしたほうが良いと思います。一瞬なんで`params[:format]`に格納されているものを取り出そうとしているのかが困惑しました。

2019-10-16 06:53 UTC, toyokappa commented on app/controllers/templates_controller.rb
> +      redirect_to new_template_path(diary_id)
renderではなくredirect_toでリダイレクトさせているのはなぜでしょうか？

2019-10-16 06:53 UTC, toyokappa commented on app/controllers/works_controller.rb
> +    @template = Template.new
この処理の意図は何でしょうか？

2019-10-16 06:53 UTC, toyokappa commented on app/controllers/works_controller.rb
> +    @template = Template.new
こちらも同様

2019-10-16 06:53 UTC, toyokappa commented on app/views/works/edit.html.erb
> +<%= render 'form', diary: @diary, work: @work, template: @template, templates: @templates, template_body: @template_body, edit_flag: true %>
controller側の方でも指摘しましたが、@templateを渡している理由がよくわからないです。
また、@template_bodyを渡している理由もよくわかりませんでした。

2019-10-16 06:53 UTC, toyokappa commented on config/routes.rb
> +  resources :templates, only: [:new, :create, :edit, :update, :index, :destroy]
今回、newとcreateの処理しか実装していないと思うので、それ以外が定義されているのは不自然かなぁと思います。（今後実装するというコンテキストを知らな人が見たら通じないと思います）

2019-10-16 06:53 UTC, toyokappa commented on app/views/works/_form.html.erb
> +function changeTemplate(val){
好みの問題になるのでどちらでもいいですが、個人的にはjsはassetsにまとめたい感じはあります。

2019-10-16 16:01 UTC, MasahiroOhsaki commented on app/controllers/templates_controller.rb
> +      redirect_to new_template_path(diary_id)
diary_idを渡す必要があったのですが、`render 'アクション'` で上手く変数を渡せなかったので、やり方のわかったredirect_toでやっていました。
試してみたら@diary_idとインスタンス変数にすることでrenderでもnewアクションに変数を渡せたので、そのように修正してみました。

2019-10-16 16:16 UTC, MasahiroOhsaki commented on app/controllers/works_controller.rb
> +    @template = Template.new
どうやら初期に色々試している時に、必要と思って書いたのがそのまま残ってしまっていたようです（collection_selectにform_withが必要だと勘違いしていて、そのform_withで参照するモデルとして@templateをコントローラーに定義していました。その際にform_withの入れ子構造にしてしまっていて…）
消して問題なさそうでしたので修正いたします。

2019-10-16 16:21 UTC, MasahiroOhsaki commented on app/views/works/edit.html.erb
> +<%= render 'form', diary: @diary, work: @work, template: @template, templates: @templates, template_body: @template_body, edit_flag: true %>
@templateを渡す部分は上記の通り必要なさそうなので削除しますね。
@template_bodyを渡している理由ですが、パーシャル_form.html.erbの中のパーシャル_work_body.html.erbのコードの中で@template_bodyを参照したいので、パーシャルにインスタンス変数を使わないようにするために渡しています。

2019-10-17 03:51 UTC, MasahiroOhsaki commented on config/routes.rb
> +  resources :templates, only: [:new, :create, :edit, :update, :index, :destroy]
実装するものをその時に定義すべきなのですね。了解です。

2019-10-17 14:29 UTC, MasahiroOhsaki commented on app/views/works/_form.html.erb
> +function changeTemplate(val){
assetsに書く際のファイルの名前の付け方が迷ったのですが、assets/javascripts/works.jsとコントローラ名と同名のjsファイルを作って、そちらにchangeTemplateを記述しました。
このファイル名のつけ方で問題は無いでしょうか？

2019-10-17 14:49 UTC, MasahiroOhsaki commented on app/controllers/templates_controller.rb
> +    session[:diary_id] = params[:format]
templatesコントローラのnewアクションへは、formatというパラメータ名でdiary_idが送られてきていて、それを`params[:diary_id]`と明示しようとするとエラーが出て上手くいかずでした。
単に `session[:diary_id] = :diary_id`としたらエラーが出なくなりました。
これで大丈夫でしょうかね？

2019-10-18 01:38 UTC, toyokappa commented on app/controllers/templates_controller.rb
> +    session[:diary_id] = params[:format]
> 明示しようとすると上手くいかず

具体的にどんなやり方しようとしてましたか？

2019-10-18 01:41 UTC, toyokappa commented on app/views/works/edit.html.erb
> +<%= render 'form', diary: @diary, work: @work, template: @template, templates: @templates, template_body: @template_body, edit_flag: true %>
`_work_body`の中で`value: template_body`としていますが、これ自体の定義している意図がわからずでした。これを定義しないと何か動作的に不具合になるんでしたっけ？

2019-10-18 01:45 UTC, toyokappa commented on app/views/works/_form.html.erb
> +function changeTemplate(val){
現状定義しているのが`cahgeTemplate`のみなので、`change_template.js`でいいかなぁと思います。`works.js`だとファイル名だけ見ても何が定義されているかは中身見ないとわからなくなってしまうと思うので。

2019-10-18 01:56 UTC, toyokappa requested changes
追加でコメントしておきました。

2019-10-18 01:56 UTC, toyokappa commented on app/controllers/templates_controller.rb
> +      render 'new', diary_id: @diary_id
`diary_id: @diary_id`は無くても動くと思いますよ。（というかこの記述は意味ないです）
逆になぜ動くようになったかは別途考察がいりそうです。

2019-10-18 01:56 UTC, toyokappa commented on app/controllers/templates_controller.rb
> +    @diary_id = session[:diary_id]
今気づきましたが`@diary_id = session[:dirary_id] = params[:format]`という形で一行で書けますね。

2019-10-19 06:16 UTC, MasahiroOhsaki commented on app/controllers/templates_controller.rb
> +      render 'new', diary_id: @diary_id
無くてもエラー出ず動きますね！
空でsubmitを押した後に変数@diaryが渡ってなくて、その後登録しようとしてもdiaryに戻らなかったので、その時にredirect_toで書いたような覚えがあり…。

2019-10-19 06:49 UTC, MasahiroOhsaki commented on app/controllers/templates_controller.rb
> +    @diary_id = session[:diary_id]
上記コメントの

>  明示的にparams[:diary_id]から取ってこれるようにしたほうが良いと思います。一瞬なんでparams[:format]に格納されているものを取り出そうとしているのかが困惑しました。


　　
と合わせてなのですが、これに対して修正を
- まず`session[:diary_id] = params[:diary_id]`にしてみたのですが、diary_idがnilでエラー。

- 次に`session[:diary_id] = :diary_id`とするとテンプレート作成画面が表示はしたのですが、登録時にdiaryに戻る際にエラー。
（ちゃんと理解していなかったのですが、これだとdiary_idの値をセッションに格納したのではなくてキーを値として格納していたということでしょうか）

としていて上手くいかずでした。
ここまで書いてて気づいたのですが、
```
params[:diary_id] = params[:format]
session[:diary_id] = params[:diary_id]
 ```
これを合わせて
`session[:diary_id] = params[:diary_id] = params[:format]`
とすれば、明示できていることになりますかね？

最終的に、下の行と併せて一行で書くということで
`@diary_id = session[:dirary_id] = params[:diary_id] = params[:format]`

と書いてみたのですが、わかりやすいコードになっているでしょうか？（ご指摘いただいたことと僕の解釈が合っているでしょうか）

2019-10-19 06:56 UTC, MasahiroOhsaki commented on app/controllers/templates_controller.rb
> +    session[:diary_id] = params[:format]
一番最後のコメントに合わせて書いてみました。

2019-10-19 07:18 UTC, MasahiroOhsaki commented on app/views/works/edit.html.erb
> +<%= render 'form', diary: @diary, work: @work, template: @template, templates: @templates, template_body: @template_body, edit_flag: true %>
ほんとだ、すみません、`value: template_body`は不要でした。
JSの理解不足でした…。get_body.js.erbで、div id="template_body"内を@template_bodyの値に置き換える、ところまで処理しているという事ですよね。

2019-10-19 12:11 UTC, toyokappa commented on app/controllers/templates_controller.rb
> +    @diary_id = session[:diary_id]
うーん、根本が理解できてなさそうです。`params[:diary_id]`から値を取得するためには、URLパラメータとして`diary_id`を渡して上げる必要があります。それに辺りURLパラメータとは何かをまず調べてみてください。その後にRailsとして指定のURLパラメータを渡す方法を調べてください。

次に、なぜ`params[:format]`に値が渡ってしまうのか？これはRailsがURLの末尾のドット以降（`.html`など）をformatとして受け取るようになっているからです。（こちらも詳しくは自分で調べてみてください）
`new_template_path(diary)`で吐き出されるURLを見てみると`/templates/new.1`というようなURLとなっていると思います。この`.1`というのがformatの部分です。本来このような形でパラメータを渡すのは間違っているので、`/templates/new?diary_id=1`というURLが生成することを目指してください。この辺りは前半で説明している内容を調べれば出てきます。

2019-10-19 12:13 UTC, toyokappa commented on app/views/works/edit.html.erb
> +<%= render 'form', diary: @diary, work: @work, template: @template, templates: @templates, template_body: @template_body, edit_flag: true %>
はい、基本的にjsの方でtemplate_bodyを書き換える処理を行っているので、`value: template_body`は不要となります。

2019-10-20 12:47 UTC, toyokappa requested changes
概ねOKそうです。細かい部分の修正お願いします。

2019-10-20 12:47 UTC, toyokappa commented on app/assets/javascripts/works.js
> +function changeTemplate(val){
このファイル不要ですね。流れ的にgitの操作がうまくできてない気がします。

2019-10-20 12:47 UTC, toyokappa commented on app/views/works/_form.html.erb
> +      <%= link_to "新規テンプレート追加", new_template_path(diary_id: diary.id) %>
👍

2019-10-20 12:47 UTC, toyokappa commented on app/views/works/edit.html.erb
> +<%= render 'form', diary: @diary, work: @work, templates: @templates, template_body: @template_body, edit_flag: true %>
以前の指摘が直ってない気がします。

2019-10-20 12:47 UTC, toyokappa commented on app/views/works/new.html.erb
> +<%= render 'form', diary: @diary, work: @work, templates: @templates, template_body: @template_body %>
こちらも。

2019-10-22 13:24 UTC, toyokappa approved these changes
LGTMです。マージして次へ進みましょう！

2019-10-22 13:38 UTC, merged