Create memo
MasahiroOhsaki/workdiary pull request #21
Opened 2019-11-09 10:38 UTC by MasahiroOhsaki

メモ機能がひとまずできました。
よろしくお願いします。

2019-11-10 02:11 UTC, toyokappa requested changes
コメントしました。確認お願いします！

2019-11-10 02:11 UTC, toyokappa commented on app/controllers/memos_controller.rb
> +    @work = Work.find params[:work_id]
ルーティングから:work_idを取らなくなったのでこちらは不要ですね。

2019-11-10 02:11 UTC, toyokappa commented on app/controllers/memos_controller.rb
> +    @memo = @work.create_memo(memo_params)
この時点で`save`処理が走ってしまっています。`build`と`create`の違いは認識する必要あありそうです。

2019-11-10 02:11 UTC, toyokappa commented on app/views/diaries/show.html.erb
> +      <td><%= link_to_if(work.memo.present?, "delete", work_memo_path(work), method: :delete, data: {confirm: "このメモを消して大丈夫？"}) {} %></td>
この辺りひとしきり`memo`が必要なときの処理だと思うので、全体的に`if work.memo.present?`のif文で囲ってしまったほうが良いと思いました。

2019-11-10 02:11 UTC, toyokappa commented on app/views/memos/_error_message.html.erb
> +<% if memo.errors.any? %>
他にも似たようなパーシャルが合った気がするので共通処理は一つのパーシャルにまとめるようにしたほうが良いと思いました。

2019-11-10 14:14 UTC, MasahiroOhsaki commented on app/views/diaries/show.html.erb
> +      <td><%= link_to_if(work.memo.present?, "delete", work_memo_path(work), method: :delete, data: {confirm: "このメモを消して大丈夫？"}) {} %></td>
なるほどです。ifでくくるようにした方が処理のまとまりがわかりやすそうですね。

2019-11-10 14:33 UTC, MasahiroOhsaki commented on app/views/memos/_error_message.html.erb
> +<% if memo.errors.any? %>
はい、memosの他にdiaries, worksにも変数のみが違う同じようなエラーメッセージがあります。
変数はパーシャルへのrenderで渡す時に記述すればそれぞれ渡せそうだなと思ったのですが、
一つのパーシャルにまとめるとしたらどのフォルダに入れておくのが妥当でしょうか？
（例えばviews/diaries/_error_message.html.erbにまとめてよいのでしょうか？それとも複数のコントローラーから呼び出されるので、views/layouts の中にパーシャルを作るなどした方がよいのでしょうか？）

2019-11-10 14:53 UTC, MasahiroOhsaki commented on app/controllers/memos_controller.rb
> +    @work = Work.find params[:work_id]
ルーティングからmemos#newを呼び出す際に、ːwork_idは必要そうなのですがどうなのでしょうかね？6行目の@memoを取り出す際にも必要かなと思い…。
ちなみにルーティングを変更したおかげでːdiary_idはとらなくなったのですが、5行目の@diaryはビューでの表示がしたいためにこのように取得しています。
（なにか認識不足でしたらすみません）

2019-11-10 14:56 UTC, MasahiroOhsaki commented on app/controllers/memos_controller.rb
> +    @work = Work.find params[:work_id]
rake routes でルートを調べると以下のようになっています。

```
            new_work_memo GET    /works/:work_id/memo/new(.:format)                                                       memos#new
           edit_work_memo GET    /works/:work_id/memo/edit(.:format)                                                      memos#edit
                work_memo PATCH  /works/:work_id/memo(.:format)                                                           memos#update
                          PUT    /works/:work_id/memo(.:format)                                                           memos#update
                          DELETE /works/:work_id/memo(.:format)                                                           memos#destroy
                          POST   /works/:work_id/memo(.:format)                                                           memos#create
```

2019-11-10 15:00 UTC, MasahiroOhsaki commented on app/controllers/memos_controller.rb
> +    @memo = @work.create_memo(memo_params)
前も同じとこで認識不足があったような気がします…再度確認します。

2019-11-11 10:41 UTC, toyokappa commented on app/controllers/memos_controller.rb
> +    @work = Work.find params[:work_id]
あー、すいません、work -> diary -> memoという関連なのかと思ってました。
diary -> work -> memo なので@diaryがいらない感じですね。

2019-11-11 10:42 UTC, toyokappa commented on app/views/memos/_error_message.html.erb
> +<% if memo.errors.any? %>
その場合は`views/shared/`直下に作るのが順当ですね。

2019-11-11 10:43 UTC, toyokappa commented on app/controllers/memos_controller.rb
> +    @diary = Diary.find @work.diary_id
こっちが不要とういことでした。

2019-11-11 10:45 UTC, toyokappa commented on app/controllers/memos_controller.rb
> +    @diary = Diary.find @work.diary_id
と思ったけど、View側でdiaryの情報使ってるんですね。
関連貼っているので呼び出し方は関連を使って`@work.diary`の方が良いかと思います。

2019-11-11 10:45 UTC, toyokappa commented on app/controllers/memos_controller.rb
> +    diary = Diary.find work.diary_id
これはいらなそうですね。

2019-11-12 02:55 UTC, MasahiroOhsaki commented
修正してプッシュしましたのでよろしくお願いします。
コードレビューしていただいてる途中であまり良くなさそうだなと思いながらも、気づいた点があったので修正したところと関係する機能を追加してしまったのですが、問題ないものでしょうか？実際の開発ではこういうケースの時はどうしますか？

追加した事項
・テンプレート新規作成でもバリデーションがかかっているので、エラーメッセージを呼び出せるように追加しました
・diaries/showの画面からも、メモを追加できるリンクをはりました

2019-11-12 03:01 UTC, MasahiroOhsaki commented
修正してプッシュしましたのでよろしくお願いします。
コードレビューしていただいてる途中であまり良くなさそうだなと思いながらも、気づいた点があったので修正したところと関係する機能を追加してしまったのですが、やらない方がいいでしょうか？実際の開発ではこういうケースの時はどうしますか？

追加した事項
・テンプレート新規作成でもバリデーションがかかっているので、エラーメッセージを呼び出せるように追加しました
・diaries/showの画面からも、メモを追加できるリンクをはりました

2019-11-15 00:17 UTC, toyokappa approved these changes
OKそうです。修正していて気づいた点の追加対応については今回みたいにコメントを残していただければ特に問題ないです！

2019-11-15 00:50 UTC, merged