Create modify
MasahiroOhsaki/workdiary pull request #24
Opened 2019-12-01 01:55 UTC by MasahiroOhsaki

## コントローラーの作成
**modify_controller**

## コントローラーに追加
**templates_controller**
- edit　編集画面　get　/templetes/:id/edit
- update　編集処理　put/pathc　/templetes/:id
- index　テンプレート一覧画面　get　/templetes
- destroy　削除処理　delete　/templetes/:id

**Categories_controller**
- edit 編集処理 get /categories/:id/edit
- update 編集処理 put/patch /categories/:id
- index カテゴリ一覧画面 get /categories
- destroy 削除処理 delete /categories/:id

## MEMO
- 「編集」＞「カテゴリ」か「テンプレート」選択＞それぞれ一覧から編集・修正できる画面
- カテゴリの名前を変更したら、既に登録されているworkデータベースのcategoryカラムも同時に更新される必要あり

2019-12-02 03:42 UTC, toyokappa requested changes
コメントしました。確認お願いします。

2019-12-02 03:42 UTC, toyokappa commented on app/controllers/categories_controller.rb
> +    category.destroy!
削除する際に、Work側に関連づいている`category_id`を`nil`に変えておかないと不整合が起きそうな気がします。
Categoryモデルの`dependent_destroy`をその様に設定しましょう。

2019-12-02 03:42 UTC, toyokappa commented on app/views/categories/_form.html.erb
> +  <% if local_assigns[:edit_flag] %>
改めてパーシャルからフラグを取るのではなく、`form.object.persisted?`等でオブジェクトの状態から取れると運用コスト下げられるかなぁと思います。

2019-12-02 03:42 UTC, toyokappa commented on app/views/categories/_form.html.erb
> +    <!--work入力画面からのカテゴリ登録かどうかで分岐　works/newではdiary_idに値が入っている-->
このコメントの書き方だとHTML吐き出した際にブラウザ側から読めてしまうので良くないです。
システム的なロジックの補足コメントを書くのであれば`<%# %>`を使うようにしましょう。

2019-12-02 03:42 UTC, toyokappa commented on app/views/categories/index.html.erb
> +        <!--categoryに紐付くworksがない場合のみそのcategoryを削除できる-->
こちらのコメントも同様です。

2019-12-02 03:42 UTC, toyokappa commented on app/controllers/categories_controller.rb
> +    category.destroy!
View側を見て気づきましたが、削除の制御を書けているんですね。それであればController側でも制御を書けておいたほうが良いと思います。（リンクが表示されていなくても`curl`コマンド等でURL自体は叩けるので）

2019-12-02 03:42 UTC, toyokappa commented on app/views/templates/_form.html.erb
> +    <!--work入力画面からのカテゴリ登録かどうかで分岐　works/newではdiary_idに値が入っている-->
こちらのコメントも。

2019-12-02 03:42 UTC, toyokappa commented on app/controllers/modify_controller.rb
> +class ModifyController < ApplicationController
命名的な問題ですが、「設定一覧」とかにニュアンスは近そうなので`Configurations`とか`Settings`とかの方が適切なのかなぁという気もします。

2019-12-03 02:26 UTC, MasahiroOhsaki commented on app/controllers/modify_controller.rb
> +class ModifyController < ApplicationController
ありがとうございます。僕もしっくりきてませんでした。Settings コントローラーに変更してみました。
・コントローラーのファイル名変更
・コントローラーの中身（クラス定義）変更
・ビューのフォルダ名変更
・ルーティング変更
・ビューのパス表記を変更

2019-12-03 15:24 UTC, MasahiroOhsaki commented on app/controllers/categories_controller.rb
> +    category.destroy!
## Categoryの削除関係について質問
コメントいただいてcategories_controllerのdestroyアクションにも制御をかけてみました（書き方はこんな感じでよいのでしょうか）

ただコンソール上で試してみたら、workとの関連があるcategoryオブジェクトを取り出してcategory.destroyで削除することができてしまうようでした。それをすると不都合が起きてしまったため、それを防ぐためCategoryモデルにもdependent: :destroyを設定するようにしました。

2019-12-03 15:25 UTC, MasahiroOhsaki commented
修正してみました！

## 追加修正
- memoのビューに問題があったので微修正しました。

2019-12-09 11:16 UTC, MasahiroOhsaki commented
## 追加修正
- memoのビューを微修正しました。
（カテゴリ名ではなくクラスの番号？で表示されていた点、submitボタンの表示をnewとeditで分岐）

## destroy周りについて
先ほど方向性を教えていただいた通り
- WorksControllerでのdestroy制御はかけず
- Categoryモデルにて、dependent: :nullifyを設定
- （Workモデルのcategoryカラムはもともとpresenceバリデーションはつけていなかったためそのまま）
やはりビュー側での不都合が出たので、一部if文にて対応していますが、いかがでしょうか。

2019-12-09 12:10 UTC, toyokappa reviewed
コメントしました！

2019-12-09 12:10 UTC, toyokappa commented on app/views/categories/index.html.erb
> +        <td><%= link_to_if(category.works.presence == nil, "delete", category_path(category), method: :delete, data: {confirm: "このカテゴリを消して大丈夫？"}) {} %></td>
コメントに書いていたView側の不都合とは具体的にどんな内容でしょう？

2019-12-09 12:10 UTC, toyokappa commented on app/views/diaries/index.html.erb
> +            <% if work.category != nil %>
`work.category.present?`の方がわかり易くないですか？

2019-12-09 13:16 UTC, MasahiroOhsaki commented on app/views/diaries/index.html.erb
> +            <% if work.category != nil %>
ですね。直しました。

2019-12-09 13:27 UTC, MasahiroOhsaki commented on app/views/categories/index.html.erb
> +        <td><%= link_to_if(category.works.presence == nil, "delete", category_path(category), method: :delete, data: {confirm: "このカテゴリを消して大丈夫？"}) {} %></td>
言葉足らずですみません。
不都合が起きるのはcategories/index.html.erbではなく、下でコメントいただいている部分（diaries/index.html.erb）の方のため、そちらの方をif文を付け足すことで対応しております。

具体的には、仮にコンソールを叩いてworkを持っているcategoryを削除した場合
そのcategoryに紐づいているworkは残る（categoryカラムがnilになる）のですが、diariesのビューでは`work.category.name`とcategoryのnameカラムを表示させるようにしているので、その部分が取得できずエラーが発生してきます。

2019-12-10 02:24 UTC, toyokappa requested changes
コメントしました。

2019-12-10 02:24 UTC, toyokappa commented on app/views/categories/index.html.erb
> +        <td><%= link_to_if(category.works.presence == nil, "delete", category_path(category), method: :delete, data: {confirm: "このカテゴリを消して大丈夫？"}) {} %></td>
なるほどです。だとするとこちらは`link_to_if`で条件追加する必要はないかと思うので、修正をお願いします。

2019-12-10 02:24 UTC, toyokappa commented on app/views/diaries/index.html.erb
> +              <%= work.category.name %>
今気づきましたが、`if文`書かなくても`&.`演算子で対応が可能そうです。`&.`が何かは検索した上で、そちらの実装に修正してみてください。

2019-12-10 09:31 UTC, toyokappa approved these changes
LGTMです！

2019-12-10 09:34 UTC, merged